#!/usr/bin/env python3
import sys, select
import serial


path = sys.argv[1]
with serial.Serial(path, timeout=1) as f:
    print(f'{path}: ready', file=sys.stderr)
    while 1:
        if f.in_waiting:
            l = f.readline()
            if not l.startswith((b'1 ', b' S1')):
                print(f'{path}: recv {len(l)} {l}', file=sys.stderr)
                pass
            print(l.decode('utf-8'))
            sys.stdout.flush()
        if select.select([sys.stdin, ], [], [], 0.0)[0]:
            l = input()
            print(f'{path}: send {len(l)} {l}', file=sys.stderr)
            f.write(l.encode('ascii') + b'\n')
            print(f'{path}: sent {len(l)} {l}', file=sys.stderr)
